// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVm6NcVpbt8MarBkFmcwJh22jfgsl2-sE',
    appId: '1:827489900120:web:7d03930b6b5392879c5c2d',
    messagingSenderId: '827489900120',
    projectId: 'chat-d09ee',
    authDomain: 'chat-d09ee.firebaseapp.com',
    storageBucket: 'chat-d09ee.appspot.com',
    measurementId: 'G-SBNY23G70X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1PJi5-wZUiaz83RNpTflqYFjpp-WfSPM',
    appId: '1:827489900120:android:849cc42ad5fbbe779c5c2d',
    messagingSenderId: '827489900120',
    projectId: 'chat-d09ee',
    storageBucket: 'chat-d09ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihYOHOTzOfh-o-J_R2DJYg79oi4DYyB0',
    appId: '1:827489900120:ios:49cbf0fe6bcc49cd9c5c2d',
    messagingSenderId: '827489900120',
    projectId: 'chat-d09ee',
    storageBucket: 'chat-d09ee.appspot.com',
    iosBundleId: 'com.example.securechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihYOHOTzOfh-o-J_R2DJYg79oi4DYyB0',
    appId: '1:827489900120:ios:49cbf0fe6bcc49cd9c5c2d',
    messagingSenderId: '827489900120',
    projectId: 'chat-d09ee',
    storageBucket: 'chat-d09ee.appspot.com',
    iosBundleId: 'com.example.securechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVm6NcVpbt8MarBkFmcwJh22jfgsl2-sE',
    appId: '1:827489900120:web:4a4b024c497d87fe9c5c2d',
    messagingSenderId: '827489900120',
    projectId: 'chat-d09ee',
    authDomain: 'chat-d09ee.firebaseapp.com',
    storageBucket: 'chat-d09ee.appspot.com',
    measurementId: 'G-25LHV097FC',
  );
}
